### ISSUE TITLE
SIWE asking for a sign on any page

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/extensions-hackathon#29]
When you first connect your wallet (/ or /submit), you get a prompt to sign:

![image](https://github.com/user-attachments/assets/4e2f88f4-a3e4-44c2-b626-965753d135c0)

This should only happen on the admin page: well, rn you get redirected to /siwe... which makes me think... do we really need it? It seems that I can sign the message on wallet connection on any page (And successfully get the auth token + able to visit /admin) cc @technophile-04 

I didn't notice this on localhost (maybe it's happening but I didn't notice), but it's happening on the live site.

**Comment by technophile-04** [comment]
Ohh my bad actually while talking with you I completely forgot that we were also using RainbowkitAuthProvider. 

Basically on SIWE Next Auth doc they had mentioned this: 

<img width="793" alt="image" src="https://github.com/user-attachments/assets/8a13a10b-ee59-42b5-b863-d0cbe6079786">


And my bad I inferred it in wrong that you have to have `/siwe` page created.

Since we have integrated [`RainbowkitAuthProvider`](https://www.rainbowkit.com/docs/authentication) rainbowkit will by default force user to sign the message as soon they sign message. So we don't require an `/siwe` page.

Just created #48 where we only force user to do SIWE if its `/admin` page and removed `/siwe` too
